### ISSUE TITLE
Should this repo be called “whosonfirst-kinds”?

### ISSUE THREAD

**Issue by dphiffer** [mapzen/whosonfirst-categories#1]
This ticket is a place to sort out how categories and kinds work, picking up from @nvkelso’s comment on Boundary Issues [Pull Request 120](https://github.com/whosonfirst/whosonfirst-www-boundaryissues/pull/120#issuecomment-219230518).
1. Should we rename this repo to `whosonfirst-kinds`?
2. How do we map the contents of this repo to PNG icons that go on the map?
3. Should we use two separate WOF properties, `wof:kind` and `wof:category`?

I compared [this repo’s categories](https://github.com/whosonfirst/whosonfirst-categories/tree/master/categories) to the icon sets from [Bubble Wrap](https://github.com/tangrams/bubble-wrap/blob/gh-pages/bubble-wrap.yaml#L229-L372) and [Refill](https://github.com/whosonfirst/whosonfirst-www-boundaryissues/tree/master/www/images/categories) (Refill is what I’m currently using in the Boundary Issues UI), and I noticed that some of the selections result in a broken image, since the icon PNG doesn’t exist.

I made a [CSV file](https://github.com/whosonfirst/whosonfirst-categories/files/266612/kinds.csv.zip) that shows each set of categories (also available as a [Google Doc](https://docs.google.com/a/mapzen.com/spreadsheets/d/1aqFHK5detTmZeFajpnobWWC42F8_T3PlcfTACCNUpNw/edit?usp=sharing)). There seems to be a good correlation between the Refill & Bubble Wrap, but they differ from this repo’s contents.

**Comment by dphiffer** [comment]
cc @thisisaaronland

**Comment by nvkelso** [comment]
They're related concepts, they should be in the same repo.

**Comment by thisisaaronland** [comment]
@nvkelso Can you elaborate / describe the following:
1. The relationship between category and kind (and any other groupings)
2. How to determine whether either or both have a corresponding icon

**Comment by dphiffer** [comment]
Here's a recap from my conversation with @nvkelso yesterday, of course none of this should be considered definitive yet:
- The categorization properties are three-tiered: `wof:kind`, `wof:kind_detail`, `wof:kind_group` (e.g., `"restaurant"`, `"fast food"`, `"food and drink"`, respectively, although those specific values aren’t decided yet)
- The word "kind" has an existing usage with vector tiles, so it seems better than "category"
- A `wof:kind` value parents `wof:kind_detail` and is parented by `wof:kind_group`
- The visual display of icons is situational (i.e., sometimes you might see the icon for `kind_group` and sometimes you might see the `kind` or `kind_detail` icon), but each possible value should include an icon filename (which could be set to a generic filename, in the absence of an existing icon file)
- Boundary Issues should be a tool for understanding how a record will appear on a map

**Comment by thisisaaronland** [comment]
Resolved. Categories are categories.
